# =======================================================================
# Permissions
# =======================================================================
iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:SendMessageBatch
      - sqs:SendMessage
    Resource:
      - Fn::GetAtt: [DeadLetterQueue, Arn]
  - Effect: Allow
    Action: cloudwatch:PutMetricData
    Resource: "*"
  - Effect: Allow
    Action:
      - logs:PutRetentionPolicy
      - logs:PutSubscriptionFilter
    Resource: "*"
  - Effect: Allow
    Action:
      - sns:Publish
    Resource:
      Ref: SNSErrorTopic
  - Effect: Allow
    Action:
      - lambda:UpdateFunctionConfiguration
    Resource: "*"

# =======================================================================
# Environment Variables
# =======================================================================
environment:
  LOG_LEVEL: DEBUG
  STAGE_NAME: ${self:custom.stageName}
  SNS_ERROR_TOPIC:
    Ref: SNSErrorTopic
  APP_NAME: ${self:service}

loggroupEvents:
  - cloudwatchEvent:
      event:
        source:
          - aws.logs
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - logs.amazonaws.com
          eventName:
            - CreateLogGroup

custom:
  stageName: ${opt:stage, self:provider.stage}
